
-- Sample data for IT Delivery Dashboard

-- Insert sample escalations with simplified schema
INSERT INTO escalations (title, description, customer, project_owner, priority, status, date_raised, resolution_eta, impact_assessment, actions_taken) VALUES
('API Performance Issues', 'Critical performance degradation in API response times affecting customer operations.', 'TechCorp Industries', 'Alex Rodriguez', 'high', 'open', '2024-06-01', '2024-06-08', 'Customer operations severely impacted. SLA breach imminent if not resolved within 24 hours. Potential revenue loss of £50K per day. Customer satisfaction at risk.', 'Infrastructure team notified and investigating. Database performance analysis initiated. Customer informed of ongoing investigation. Backup systems activated to mitigate impact.'),
('Security Vulnerability Detected', 'High-severity security vulnerability found in authentication system requiring immediate attention.', 'InnovateCorp', 'Sarah Johnson', 'critical', 'in_progress', '2024-05-15', '2024-05-20', 'Critical security risk. Potential data breach if exploited. Compliance violations possible. Customer trust at stake.', 'Security team engaged. Patch development in progress. Customer notified with mitigation steps. External security audit scheduled.'),
('Database Migration Delays', 'Database migration project experiencing significant delays affecting go-live timeline.', 'GlobalTech', 'Mike Chen', 'medium', 'open', '2024-05-20', '2024-06-15', 'Project timeline at risk. Client go-live date may be missed. Additional resources may be required.', 'Migration team working extended hours. Alternative migration strategy being evaluated. Client stakeholders informed of potential delays.'),
('Resource Shortage - Java Developers', 'Critical shortage of experienced Java developers for enterprise project delivery.', 'DataFlow Systems', 'Emily Davis', 'high', 'open', '2024-05-25', '2024-06-10', 'Project delivery at risk due to lack of skilled resources. Timeline extension likely required. Budget impact anticipated.', 'HR team actively recruiting. Contract resources being evaluated. Existing team members upskilling through training programs.'),
('Client Communication Breakdown', 'Breakdown in communication with key client stakeholder affecting project progress and requirements clarity.', 'CloudSync Ltd', 'James Wilson', 'medium', 'resolved', '2024-04-10', '2024-04-25', 'Project requirements unclear. Decision-making delayed. Team productivity impacted. Client relationship strained.', 'Senior leadership meeting scheduled with client. Communication protocols established. Weekly stakeholder calls implemented. Project requirements documented and approved.');
